# Generated by Django 4.2 on 2023-05-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='socialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('media', models.URLField(blank=True, null=True, verbose_name='Link media')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha actualizacion')),
            ],
            options={
                'verbose_name': 'Redes sociales',
                'verbose_name_plural': 'Redes sociales',
            },
        ),
    ]
