# Generated by Django 4.2 on 2023-05-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='creado',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='actualizado',
            new_name='updated',
        ),
    ]
