# Generated by Django 4.2 on 2023-05-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_media_socialmedia_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(default=True, max_length=500, verbose_name='Icono svg o boostrap'),
            preserve_default=False,
        ),
    ]
