# Generated by Django 4.2 on 2023-05-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_alter_project_created_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(default=True, verbose_name='Fecha actualizacion'),
        ),
    ]
