# Generated by Django 4.2 on 2023-05-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0008_alter_project_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(upload_to='media', verbose_name='Imagen'),
        ),
    ]
