# Generated by Django 4.2 on 2023-05-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0010_alter_project_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default=True, verbose_name='Direccion web'),
            preserve_default=False,
        ),
    ]
