# Generated by Django 4.2 on 2023-05-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0012_alter_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Direccion web'),
        ),
    ]
