# Generated by Django 4.2 on 2023-05-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0013_alter_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null='Agrega la dieccion', verbose_name='Direccion web'),
        ),
    ]
