# Generated by Django 4.2 on 2023-05-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0015_alter_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.CharField(default=True, max_length=20, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
