# Generated by Django 4.2 on 2023-05-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0016_project_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Link facebook'),
        ),
        migrations.AddField(
            model_name='project',
            name='instragam',
            field=models.URLField(blank=True, null=True, verbose_name='Link instagram'),
        ),
        migrations.AddField(
            model_name='project',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Link twitter'),
        ),
    ]
