# Generated by Django 4.2 on 2023-05-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0018_socialmedia_remove_project_facebook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='instragam',
            new_name='instagram',
        ),
    ]
