# Generated by Django 4.2 on 2023-05-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0019_rename_instragam_socialmedia_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=True, verbose_name='Fecha creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha actualizacion'),
        ),
    ]
