# Generated by Django 4.2 on 2023-05-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0020_socialmedia_created_socialmedia_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
