# Generated by Django 4.2 on 2023-05-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0021_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
