# Generated by Django 4.2 on 2023-05-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0022_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['-created'], 'verbose_name': 'Redes sociales', 'verbose_name_plural': 'Redes sociales'},
        ),
    ]
