# Generated by Django 4.2 on 2023-05-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0023_alter_socialmedia_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='updated',
        ),
    ]
