# Generated by Django 4.2 on 2023-05-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0024_remove_socialmedia_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Redes sociales', 'verbose_name_plural': 'Redes sociales'},
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha actualizacion'),
        ),
    ]
