# Generated by Django 4.2 on 2023-05-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0025_alter_socialmedia_options_socialmedia_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='twitter',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='media',
            field=models.URLField(blank=True, null=True, verbose_name='Link media'),
        ),
    ]
