# Generated by Django 4.2 on 2023-05-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0027_rename_updated_socialmedia_actualizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(default=True, max_length=50, verbose_name='Titulo'),
            preserve_default=False,
        ),
    ]
