# Generated by Django 4.2 on 2023-05-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0028_socialmedia_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='creado',
        ),
    ]
