# Generated by Django 4.2 on 2023-05-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0029_remove_socialmedia_actualizado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='socialMedia',
        ),
    ]
